[supabase]
url = "https://pqkzgypsllkffqnvdsyn.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxa3pneXBzbGxrZmZxbnZkc3luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MDI3ODQsImV4cCI6MjA1MDQ3ODc4NH0.46pHbTqJX1cMZqgQ6pIQyPj6h2HxZq8sQZ0YwqRwQ4Y"
