[google_sheets]
type = "service_account"
project_id = "football-prediction-tracker"
private_key_id = "46ffc0d73b584b8a94683ab1ccd8ee719ed621f8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDm6GcKtXXRGG7e
tgdBhXUiU/sZZe0r31jLGlZavKolDMT0XStYa6L8IBrJKqRnwXVaWFJebmDmr9o5
uHAfMFNoCaouX/Lj/PNMpRXMw3+2AiBc1q2ddO8zN96v3j60pXdU38u52sy2V3dH
YIhiZ/dyWP0OhJEVgqV2wqtdzJy6BsqzYF4PjMX7+OU4D+Ai4hLQAUeJSFgpWJlM
H6tZ4Rj3oYnBQSXSati4cAUJbGAgQupiULGeZMq1yrUdyne6HXwnEqNhS/OGiUQE
KO66C2Nsw1INW+Md/4oJdj8cP4dVT9nsTlaeju7habUvZvTRaTt/dJYvQilNKs7N
ziEzUPItAgMBAAECggEAGpbxBK3sLQGaBMnj0IL4f9U5YU2YL9jmje7Qul6m3iDY
DkarTuGIMW3V/8vKBkukAp0QkSC3RmFCKSrouGK1fBG+19vDKcdPUghhmAR8MJ6S
kPZEpFDamaSJn2lhgaZbNToXKOX99FJioSTH18MenruKGnGgDmDOwnv8xU6iTpZx
IV8Njx/jvuLSFi1Zr5QuvMNJPJ7B+OJTi99z7YdNzGbyXDtR5AsTATM4Z9AC6j+a
Ki4MG/b7Z3ambdbNvITSHCrIXYgn/aI7n4083sglzgptKd4RgwSphUyC8H8KIQBO
GpUt0ebNJLlsrJIFKAt6YAxKdeJeqcYunLSZk5uA+QKBgQD2pW1fxMvltywbD+uu
o/vT5wlJc5BUNTIWszyFNdkpXHmBDpjckttQG22+e3omqUrH3E1U16xoLuDRN4jQ
Om1pMagIQnUTT/z1+NPuyIFHhzRmz7nhVMyVbJ3eSs6TesxYu3hitNLg3iVfH+tE
67Ku5vCvVrPMbarSAGkf2VfzKQKBgQDvqi2/lwDKDrnpvyNoyES3SKCtdtQxYyQl
fekzy4EEfIrDYYTB3LjSzLZfLj8z1VbhsprQVtfABquLopMMG8+zrChDGXZGJaFj
F3SRFgwclfG597zGg1KRw/+b+Bq6M7JSX7b1wCRp9QjOhGwZzJs4J6Jwi77pcMI7
ehEU2XlLZQKBgQCDBXHKlAI0b0+QuK5cQWQ/NtXqHOeos/F9uY0GvoozvJoXAqgV
VDYIoel0bKeA7iF5df/meANv/KcUvMmCw+bnIKfAa31B2xXnnF0I1Z5HXv1pOCPo
HWHoZqCeO2LtWShAYqYa2S/EoH19wLj8DbEH1Eo6+nXcvM0nbWxqrMxZsQKBgFfV
FGMMohtq/jNt+zohex14nnoz/FwFK3AaDucOg7/zLJ+iE5dAnvOSVpvXRQ5n9ylL
3XTQ/sy/JQtNj3p2js4YH8FHiZL3o4e/RtcNL28ifK5c3nAaHJ6TKBAvAwyOeaG6
tkCmJDI4vPuCiGOEGrafv+ZjMJo42tYVTEFJ2iwJAoGAH/VoGme7YzCTPP4WO5PX
OInc2S0cHw746ahTfihkLoWLF9K6ivMQ4rXJzr1uu9BqRtEEFA9x9xnrbRYaUjh0
amVrpxvTopWGOWQVB0jK2cjWaFzP1aW/+b3AWxodfk3XyTAWukerflpbo/SNwxOM
ala4Bh7y8+r64oOwWsUyecY=
-----END PRIVATE KEY-----"""
client_email = "ozone-football@football-prediction-tracker.iam.gserviceaccount.com"
client_id = "104388796973647551477"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ozone-football%40football-prediction-tracker.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
