[google_sheets]
type = "service_account"
project_id = "football-prediction-tracker"
private_key_id = "65077485885dbc0704bfe11959470039039dcea5"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCdcJkRKvlNUYBS
csZOs0KAyxgNnJ1zoTbCMQYs5JyPEMX0xYZ/pfVWDGgh3KerAw2EWfReaMWNH1sD
2FMhe+ny/BSpNoTJEb7UP4aq64kJyxr7JfHxi1xbPNAy3wUrIJd/HFDEo9HTUuXL
6axDx7l5AvTRJQyIk7bYVgHexLU2XL+eey4Rqmykt7FWHYv0Q1amotfSztm6jG1N
xQaWkP5QSjpHRrvqr/gVxZK5Fcq44Qds+IGW6YNyFVFi2wezFMR1Ec3Wm9UaBqr4
4Y6Wtrm1FeID3btk+KkgNB7NGfxsTpyD/qjQopxZOZnLqfB2dF1N91fIQOD+PkiV
tf2Th1w/AgMBAAECggEAR0eszXSG5aYiMnHrbcNENzp8O+Ft+eWB/L6kXJvuc+l0
roLlh5J0No6scLRNpyPdMVBmzn2h/2g0VVPSI2VOQOg3VHst+DjUDJVsW6MC6s+t
egqudR0S5e3tFzMYzHNXk8GWocjHnWU5TC6SAygARZT8kVo0R/uUu3KJKzolDySN
lJTIXqBk8wggura+tFS7+M54ZhDdZ+FeR7PRmvekseypN6RSJsi9Rtl5ndAq42SZ
HmsXrlV4G0ftWdMKweEsTxZJhh6QPNx+HVk9uDw6zA8rMftoFPn6EQT4KLhh7SxU
j6GJjh9PFtv5AcRI0e2uMM9uThdWWm82raO67PVoRQKBgQDXNXE503JXbksmV1/0
a9VMBVWVn/dyBAgpBLfI8RuREQ5XHY7ZPYB+YdRmQB6vAYBkYbr46p3J6AVqi0/0
caWYrVPL3JvvFiF9YD4qUyfU4wsEISoVNNqREjRBhvQe9YlXjtzDvqi3SJha6LPc
4Cg/D3rVQNtkTgs40eJgtrWd7QKBgQC7SAnoNCcHgyRKm2nGAqFdoRYrE2UltmFt
H920B8MFAD0+uRPfY25714IPkAQtev7yzJnEwxSelXjbnXHMoiO/2TMjTEcnCPdl
W/BE5urjNpUkdbBDH93XoYElbT6VHopX/sGA2kAUhmukaYfsrrbKlI+GSllh+oKb
50Qgntn9WwKBgHv47E3McczN23qt0Lfjuo69b+zupsPGcND4R8r4odGyiplCjLy2
QiQLxShV/ZcA/W5WIjgsJ1NdVmlm8Vs2cJeAGYqRfj5/eDFaVNVa69ImLH1ngW+P
7+ysGPA6hryi40hOIvycA2L57dJIxPwTIPwatb7NStUAZFSKC6d8+SiNAoGAG/5U
nMTO4KyVjCFW2iYigKBHdADeKZjtTyZoOTS/zcuPXATGF6oBJbm80x6vwSyVVy2F
/oc6Wcn12r3Z+MBzn4WTwz7vk8IfWKM5ctMhYP0TpfOBeUcWHdkiOLnvlNKP0z9d
JSl6UpcVF+o+Sv6CjB1Qpr4ORjrvsuYKpOWZp+kCgYA1cumUDFwphLbvxHZx91ff
5LR+X35bplOVlaE/ajKdA8TnuSkZMv5TAtqOatKGPHcP+NC92Wd4v1wMnxdcDiLE
S5sWyjEhQKrg7W1nK4CvTGAB1+9GEBGLDO/Gl0j7Mi1Zkrf6KUGNREZKA3dBxpkm
C7EnaaSubUbPYWI5Bqmcgg==
-----END PRIVATE KEY-----"""
client_email = "ozone-football@football-prediction-tracker.iam.gserviceaccount.com"
client_id = "104388796973647551477"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ozone-football%40football-prediction-tracker.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
